### ISSUE TITLE
I get unkonw 'voice-button' is not a known element while using it with angular

### ISSUE THREAD

**Issue by Abdulrahman-Khalid** [googlecreativelab/obvi#4]
I want to use it with **ionic/angular** but I get 'voice-button' is not a known element:
1. If 'voice-button' is an Angular component, then verify that it is part of this module.
2. If 'voice-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by sam17896** [comment]
as it says add CUSTOM_ELEMENTS_SCHEMA in your NgModule

follow this link: https://vaadin.com/learn/tutorials/using-web-components-in-angular#:~:text=By%20default%2C%20Angular%20assumes%20that,use%20for%20creating%20the%20form.

**Comment by Sathyamurthy-tammina** [comment]
@Abdulrahman-Khalid could you implement this in Angular? I tried but i get 404 for voicebutton.js and webcomponent-bundle.js. It would be great help in letting me know how could you implement in angular. Thank you.
